### ISSUE TITLE
mettre en place le CI/CD sous netlify

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-front-A2019#1]
déployer l'application des compteurs en ligne sous netlify
poster ici le lien vers votre app.

**Comment by LukaLam** [comment]
Lien netfily : 
https://eloquent-kowalevski-1a9c74.netlify.com/

Luka LAMBALOT

**Comment by hicham-arahhou** [comment]
Netlify app: https://mystifying-galileo-672154.netlify.com/

Hicham ARAHHOU

**Comment by KevinFritsch** [comment]
Netlify App : https://angular-kevinfritsch.netlify.com/

Kevin FRITSCH

**Comment by ArnaudBistel** [comment]
Netlify App : https://arnaud-bistel-counters.netlify.com/

Arnaud Bistel

**Comment by NathanBodet** [comment]
Lien Netlify :) : https://musing-knuth-21fb89.netlify.com/
Nathan Bodet

**Comment by ljl19971006** [comment]
Netlify lien：https://angularfront.netlify.com/
LI Jiale

**Comment by 125241576** [comment]
Netlify lien：https://xuhh-counters.netlify.com/
XU Honghao

**Comment by haolingzhang1** [comment]
Netlify lien : https://pensive-blackwell-dc56c2.netlify.com/  

ZHANG Haoling

**Comment by deove** [comment]
Netlify lien: https://suspicious-pasteur-b04ef4.netlify.com/

YAN ZEYU

**Comment by FeiyiZHAO** [comment]
Netlify lien : https://angular-fy-counters.netlify.com
Feiyi ZHAO

**Comment by BastG57** [comment]
Netlify : https://bastg57counters.netlify.com
GAUJOUR Bastien

**Comment by TheoCollignon** [comment]
Lien Netlify : https://theocollignon-frontend.netlify.com/
Théo COLLIGNON

**Comment by Qiao6651** [comment]
Lien Netlify : https://nervous-nobel-2590c5.netlify.com/
QIAO HE

**Comment by EnzoP26** [comment]
Lien Netlify : https://epic-stallman-f550f2.netlify.com/
Enzo PALERMO

**Comment by wakkoyankee** [comment]
Lien Netlify : https://hadrien-rothea.netlify.com/
Hadrien ROTHEA

**Comment by AurelienVasseur** [comment]
Netlify app : https://jolly-neumann-a525f1.netlify.com/
Aurélien VASSEUR

**Comment by Oumaimakhalil** [comment]
Netlify : https://oumaimacounters.netlify.com

Oumaima KHALIL

**Comment by meldBayi** [comment]
Netlify link: https://bayidore-frontend.netlify.com
DORE Bayi Elsa Emmanuella

**Comment by yaosonia** [comment]
Netlify link : https://relaxed-visvesvaraya-11ff16.netlify.com/

Yao Sonia

**Comment by Aicanama** [comment]
Netlify app : https://front-lpa2-imelouno.netlify.com/
MELOUNOU Inès

**Comment by YosefBayoude** [comment]
Netlify App : https://frontend-yosef.netlify.com/
Yosef BAYOUDE IZOUKA

**Comment by yaosonia** [comment]
Nestify App: https://compassionate-borg-454804.netlify.com/

Yao Sonia

**Comment by meldBayi** [comment]
Netlify App link: https://bayidore-frontendpjct.netlify.com/
Bayi DORE

**Comment by QuentinGchrd** [comment]
Netlify App :
https://frontend-qguichard.netlify.com
Quentin GUICHARD

**Comment by Fabiensamj** [comment]
https://front-end-a19.netlify.com
Fabien SAM

**Comment by FlavienGtlt** [comment]
Flavien GENTILT

https://projet-front-a19-gentilt.netlify.com/

**Comment by valent1chateau** [comment]
https://frontendfw19.netlify.com/

valentin castellon

**Comment by LPA2-Automne2016** [comment]
:+1:
