### ISSUE TITLE
mettre en place l'incrément du compteur

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-front-A2019#2]
poster ici:
un lien vers la page web livrée sous netlify
un lien vers votre projet sous github

**Comment by wakkoyankee** [comment]
Netlify : https://hadrien-rothea.netlify.com/
Github : https://github.com/wakkoyankee/AppAng 
J'incremente :  https://lp4asgadot.herokuapp.com/counters/2. Le 3 n'existe pas. 
Hadrien Rothea

**Comment by LukaLam** [comment]
Netlify : https://eloquent-kowalevski-1a9c74.netlify.com/
Github : https://github.com/LukaLam/AngularApp
Luka LAMBALOT :)

**Comment by KevinFritsch** [comment]
Netlify : https://distracted-curran-0af9d1.netlify.com/
GitHub : https://github.com/KevinFritsch/angularApp

Kevin Fritsch

**Comment by NathanBodet** [comment]
Netlify : https://condescending-goldwasser-2d1476.netlify.com/
GitHub : https://github.com/NathanBodet/ProjetLP4A_frontend
Même compteur 3 fois car des personnes ont détruit les compteurs existants...

Nathan Bodet

**Comment by Julia185** [comment]
ROLLAND Julia 

Netlify : https://frontend-jrolland.netlify.com/
GitHub : https://github.com/Julia185/projet-front-A2019

**Comment by Aicanama** [comment]
Netlify : https://front-lpa2-imelouno.netlify.com/
GitHub : https://github.com/Aicanama/projet-front-LPA2

MELOUNOU Inès

**Comment by deove** [comment]
Netlify : https://serene-lamarr-fca499.netlify.com/
GitHub : https://github.com/deove/frontend

YAN ZEYU

**Comment by Fabiensamj** [comment]
netlify : https://front-end-a19.netlify.com
github : https://github.com/Fabiensamj/projet-front-2019

Fabien SAM

**Comment by EdgarDupont** [comment]
Netlify: https://brave-agnesi-8c1643.netlify.com/
Github: https://github.com/EdgarDupont/FrontEnd

Dupont Edgar

**Comment by Bantou96** [comment]
Netlify : https://app-frontend-bantou.netlify.com/
Github : https://github.com/Bantou96/frontend

FALL Cheikh Ahmed Tidiane

**Comment by 125241576** [comment]
Netlify : https://xuhh-counters.netlify.com/
Github : https://github.com/125241576/projet-front-A2019
XU Honghao

**Comment by YosefBayoude** [comment]
Netlify : https://frontend-yosef.netlify.com/
Github : https://github.com/YosefBayoude/frontend.git
Yosef BAYOUDE IZOUKA

**Comment by AurelienVasseur** [comment]
Netlify : https://jolly-neumann-a525f1.netlify.com/
Github : https://github.com/AurelienVasseur/Projet-LP4B-frontend

Aurélien VASSEUR

**Comment by FlavienGtlt** [comment]
Netlify: https://projet-front-a19-gentilt.netlify.com/
Github: https://github.com/FlavienGtlt/projet-front-a19
Flavien GENTILT

**Comment by haolingzhang1** [comment]
Netlify: https://pensive-blackwell-dc56c2.netlify.com/
Github: https://github.com/haolingzhang1/front-end_LP4A
Haoling ZHANG

**Comment by niggadou95** [comment]
Netlify : https://appli-frontend.netlify.com/
Github : https://github.com/niggadou95/frontend
DIEYE PAPE DOUDOU

**Comment by ArnaudBistel** [comment]
Netlify : https://arnaud-bistel-counters.netlify.com/
Github : https://github.com/ArnaudBistel/frontend

Arnaud Bistel

**Comment by QuentinGchrd** [comment]
Netlify: https://frontend-qguichard.netlify.com/
Github: https://github.com/QuentinGchrd/projet-frontend

Quentin GUICHARD

**Comment by hicham-arahhou** [comment]
Netlify : https://mystifying-galileo-672154.netlify.com/
Github : https://github.com/hicham-arahhou/LP4A-frontend-A2019
Heroku : https://lp4a-backend-a2019.herokuapp.com/counters

Hicham ARAHHOU

**Comment by yaosonia** [comment]
Netlify: https://thirsty-meitner-4fc53a.netlify.com/
Github: https://github.com/yaosonia/frontend

Sonia YAO

**Comment by ljl19971006** [comment]
Netlify:  https://angularfront.netlify.com/
Github: https://github.com/ljl19971006/front-angular2019

Jiale LI

**Comment by valent1chateau** [comment]
netlify: https://frontendfw19.netlify.com/
github: https://github.com/valent1chateau/frontend_FW19_LPA2/tree/master

valentin castellon

**Comment by TheoCollignon** [comment]
Netlify : https://theocollignon-frontend.netlify.com/
Github : https://github.com/TheoCollignon/Frontend-LP4A

Theo COLLIGNON

**Comment by Oumaimakhalil** [comment]
Netlify: https://oumaimakhalil.netlify.com/
Github: https://github.com/Oumaimakhalil/projet-front-LPA2

KHALIL Oumaima (y)

**Comment by OualidBougzime** [comment]
Netlify : https://front-end-oualid.netlify.com/
Github : https://github.com/OualidBougzime/Front-End

Oualid BOUGZIME

**Comment by EnzoP26** [comment]
Netlify : https://epic-fail.netlify.com/
Github : https://github.com/EnzoP26/frontend

Enzo PALERMO

**Comment by FeiyiZHAO** [comment]
Netlify : https://angular-fy-counters.netlify.com/
Github : https://github.com/FeiyiZHAO/lp4a-front

Feyi ZHAO

**Comment by meldBayi** [comment]
Netlify : https://bayidore-frontendpjct.netlify.com/
Github : https://github.com/meldBayi/Projet-frontend-angular

Bayi DORE

**Comment by BastG57** [comment]
Netlify : https://bastg57counters.netlify.com
Github : https://github.com/BastG57/Projet-Frontend-A2019
GAUJOUR Bastien
