### ISSUE TITLE
mettre en place la navigation angular 

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-front-A2019#3]
modifier la sidebar pour inclure les liens vers les compteurs.
lorsque l'on clique sur un lien à gauche, cela doit naviguer vers /counter/:id et afficher le compteur en question.
tuto angular: https://angular.io/tutorial/toh-pt5#add-a-hero-detail-route

poster ici le lien vers l'appli sous netflify et le lien vers le projet github

**Comment by hicham-arahhou** [comment]
Netlify : https://mystifying-galileo-672154.netlify.com/
Github : https://github.com/hicham-arahhou/LP4A-frontend-A2019

Hicham ARAHHOU

**Comment by haolingzhang1** [comment]
Netlify: https://pensive-blackwell-dc56c2.netlify.com/
Github: https://github.com/haolingzhang1/front-end_LP4A
HaolingZHANG

**Comment by FeiyiZHAO** [comment]
Netlify : https://angular-fy-counters.netlify.com/
Github : https://github.com/FeiyiZHAO/lp4a-front

Feiyi ZHAO

**Comment by haolingzhang1** [comment]
Netlify: https://pensive-blackwell-dc56c2.netlify.com/
Github :https://github.com/haolingzhang1/front-end_LP4A

HaolingZHANG

**Comment by AurelienVasseur** [comment]
Netlify: https://jolly-neumann-a525f1.netlify.com/
Github: https://github.com/AurelienVasseur/Projet-LP4B-frontend

Aurélien VASSEUR

**Comment by KevinFritsch** [comment]
Netlify: https://angular-kevinfritsch.netlify.com/
Github: https://github.com/KevinFritsch/angularApp

Kévin FRITSCH

**Comment by TheoCollignon** [comment]
Netlify : https://theocollignon-frontend.netlify.com/
Github : https://github.com/TheoCollignon/Frontend-LP4A

Théo COLLIGNON

**Comment by 125241576** [comment]
Netlify : https://xuhh-counters.netlify.com/
Github : https://github.com/125241576/projet-front-A2019
Honghao XU

**Comment by deove** [comment]
Netlify :  https://kind-hypatia-995a3e.netlify.com/
GitHub :  https://github.com/deove/lastfront

YAN ZEYU

**Comment by BastG57** [comment]
Netlify : https://bastg57counters.netlify.com/
GitHub : https://github.com/BastG57/Projet-Frontend-A2019
GAUJOUR Bastien

**Comment by ArnaudBistel** [comment]
Netlify: https://arnaud-bistel-counters.netlify.com/
GitHub: https://github.com/ArnaudBistel/frontend

Arnaud Bistel

**Comment by wakkoyankee** [comment]
Netlify: https://hadrien-rothea.netlify.com/
GitHub: https://github.com/wakkoyankee/AppAng

Hadrien Rothea

**Comment by Fabiensamj** [comment]
Netlify : https://front-end-a19.netlify.com
Github : https://github.com/Fabiensamj/projet-front-2019

Fabien SAM

**Comment by Qiao6651** [comment]
Netlify: https://infallible-mirzakhani-975e5a.netlify.com
Github: https://github.com/Qiao6651/last-front

HE Qiao

**Comment by YosefBayoude** [comment]
Netlify: https://frontend-yosef.netlify.com/
Github: https://github.com/YosefBayoude/frontend
Yosef BAYOUDE IZOUKA

**Comment by Aicanama** [comment]
Netlify: https://front-lpa2-imelouno.netlify.com
Github: https://github.com/Aicanama/projet-front-LPA2
MELOUNOU Inès

**Comment by Julia185** [comment]
Julia ROLLAND

Netlify : https://frontend-jrolland.netlify.com/
GitHub : https://github.com/Julia185/projet-front-A2019

**Comment by Oumaimakhalil** [comment]
Netlify: https://oumaimakhalil.netlify.com
Github: https://github.com/Oumaimakhalil/projet-front-LPA2

KHALIL Oumaima

**Comment by FlavienGtlt** [comment]
Flavien GENTILT

Github: https://github.com/FlavienGtlt/projet-front-a19
Netlify: https://projet-front-a19-gentilt.netlify.com/

**Comment by Bantou96** [comment]
Netlify: https://app-frontend-bantou.netlify.com/
Github: https://github.com/Bantou96/frontend

FALL Cheikh Ahmed Tidiane

**Comment by LukaLam** [comment]
Netlify : https://eloquent-kowalevski-1a9c74.netlify.com/
Github : https://github.com/LukaLam/AngularApp

Luka LAMBALOT

**Comment by OualidBougzime** [comment]
Netlify : https://front-end-oualid.netlify.com/
Github : https://github.com/OualidBougzime/Front-End

Oualid BOUGZIME

**Comment by yaosonia** [comment]
Netlify: https://thirsty-meitner-4fc53a.netlify.com/
GitHub: https://github.com/yaosonia/frontend

Sonia Yao

**Comment by valent1chateau** [comment]
netlify : https://frontendfw19.netlify.com
github : https://github.com/valent1chateau/frontend_FW19_LPA2

valentin castellon

**Comment by QuentinGchrd** [comment]
Netlify: https://frontend-qguichard.netlify.com/
Github: https://github.com/QuentinGchrd/projet-frontend

Quentin GUICHARD

**Comment by EnzoP26** [comment]
Netlify : https://agitated-swirles-499e61.netlify.com/
Github https://github.com/EnzoP26/frontend

Enzo PALERMO

**Comment by niggadou95** [comment]
Netlify : https://appli-frontend.netlify.com/
Github : https://github.com/niggadou95/frontend
Dieye Pape Doudou

**Comment by meldBayi** [comment]
Netlify: https://bayidore-frontendpjct.netlify.com/
Github: https://github.com/meldBayi/Projet-frontend-angular
Bayi Doré

**Comment by ljl19971006** [comment]
Netlify: https://angularfront.netlify.com/
Github: https://github.com/ljl19971006/front-angular2019
JIALE LI
